export enum ASIDE_CONTENT_TYPES {
  APPLY_FORM_LINKS,
  RANKINGS,
  COMMUNITY_PROJECTS,
  POPULAR_NOMINATIONS,
  NEWS,
}

interface AsideContentMap {
  [key: string]: ASIDE_CONTENT_TYPES[];
}

export const ASIDE_CONTENT_BY_PATH: AsideContentMap = {
  "/projects/rankings": [
    ASIDE_CONTENT_TYPES.APPLY_FORM_LINKS,
    ASIDE_CONTENT_TYPES.POPULAR_NOMINATIONS,
    ASIDE_CONTENT_TYPES.COMMUNITY_PROJECTS,
    ASIDE_CONTENT_TYPES.NEWS,
  ],
  "/projects/community": [
    ASIDE_CONTENT_TYPES.APPLY_FORM_LINKS,
    ASIDE_CONTENT_TYPES.POPULAR_NOMINATIONS,
    ASIDE_CONTENT_TYPES.RANKINGS,
    ASIDE_CONTENT_TYPES.NEWS,
  ],
  "/projects/nominations": [
    ASIDE_CONTENT_TYPES.APPLY_FORM_LINKS,
    ASIDE_CONTENT_TYPES.RANKINGS,
    ASIDE_CONTENT_TYPES.COMMUNITY_PROJECTS,
    ASIDE_CONTENT_TYPES.NEWS,
  ],
  "/nominate/community": [
    ASIDE_CONTENT_TYPES.COMMUNITY_PROJECTS,
    ASIDE_CONTENT_TYPES.NEWS,
  ],
  "/nominate/audit": [ASIDE_CONTENT_TYPES.RANKINGS, ASIDE_CONTENT_TYPES.NEWS],
  "/project/:slug": [ASIDE_CONTENT_TYPES.RANKINGS, ASIDE_CONTENT_TYPES.NEWS],
  "/nomination/:id": [ASIDE_CONTENT_TYPES.RANKINGS, ASIDE_CONTENT_TYPES.NEWS],
  "/settings": [
    ASIDE_CONTENT_TYPES.COMMUNITY_PROJECTS,
    ASIDE_CONTENT_TYPES.NEWS,
  ],
  "/saved/nominations": [ASIDE_CONTENT_TYPES.NEWS],
};
